version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - './.env'
    environment:
      POSTGRES_PASSWORD: 455701
  web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - db
    env_file:
      - './.env'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "8000:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media

